//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int IdCliento { get; set; }
        public string Documento { get; set; }
        public string NombreCompleto { get; set; }
        public string email { get; set; }
        public string Telefono { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
