//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLECOMPRA = new HashSet<DETALLECOMPRA>();
            this.DETALLEVENTA = new HashSet<DETALLEVENTA>();
        }
    
        public int IdProducto { get; set; }
        public string Descripcion { get; set; }
        public int cantidadDisponible { get; set; }
    
        public virtual ICollection<DETALLECOMPRA> DETALLECOMPRA { get; set; }
        public virtual ICollection<DETALLEVENTA> DETALLEVENTA { get; set; }
    }
}
