//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int Documento { get; set; }
        public string Categoria { get; set; }
        public string NombreCompleto { get; set; }
        public string email { get; set; }
        public string Contraseña { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
